apiVersion: apps/v1
kind: Deployment
metadata:
  name: clearml-agent-services
  namespace: clearml
  labels:
    app: clearml-agent-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clearml-agent-services
  template:
    metadata:
      labels:
        app: clearml-agent-services
    spec:
      containers:
        - name: clearml-agent
          image: clearml/clearml-agent-services:latest
          imagePullPolicy: Always
          args: ["--services-mode", "--queue", "services", "--cpu-only"]
          env:
            - name: CLEARML_API_HOST
              value: "http://clearml-apiserver:8008"
            - name: CLEARML_WEB_HOST
              value: "http://clearml-webserver:8080"
            - name: CLEARML_FILES_HOST
              value: "http://clearml-fileserver:8081"
            - name: CLEARML_API_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: clearml-conf
                  key: test_user_key
            - name: CLEARML_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: clearml-conf
                  key: test_user_secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
